# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: matchmycolor.ColibriBeta
PackageVersion: 25.1.3.15604
InstallerType: exe
InstallerSwitches:
  Silent: /s
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.Runtime.8
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
  - PackageIdentifier: Microsoft.DotNet.AspNetCore.8
  - PackageIdentifier: Microsoft.VCRedist.2015+.x86
Installers:
- Architecture: x86
  InstallerUrl: https://cdn.matchmycolor.com/colibri/25.1.3/Colibri_25.1.3-beta.9.exe
  InstallerSha256: 64F517B17D2D5091992C2BE4CD238A8C5DAC008D96A21AFF3E3E1E065ACC8920
ManifestType: installer
ManifestVersion: 1.10.0
