# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Ablaze.Floorp
PackageVersion: 12.3.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
Commands:
- floorp
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- url
- webp
- xht
- xhtml
ReleaseDate: 2025-10-21
Scope: machine
InstallerLocale: en-US
InstallerType: nullsoft
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
ElevationRequirement: elevatesSelf
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Floorp-Projects/Floorp/releases/download/v12.3.2/floorp-windows-x86_64.installer.exe
  InstallerSha256: 4E955254DA74BD5BB71923F7959396005A8F96A8073BDEF00E6EC0CCA81911EC
  AppsAndFeaturesEntries:
  - DisplayName: Ablaze Floorp (x64 en-US)
    ProductCode: Ablaze Floorp 12.3.2 (x64 en-US)
ManifestType: installer
ManifestVersion: 1.10.0
