# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CoralCreek.SQLiteExpert.Professional
PackageVersion: 6.2.2.736
InstallerType: inno
Scope: machine
ReleaseDate: 2026-09-26
Installers:
- Architecture: x86
  InstallerUrl: https://www.sqliteexpert.com/v6/SQLiteExpertProSetup32.exe
  InstallerSha256: 5A6F251D0224A430DE273F1F868EDEC3000307D29BF460C51DC61E3F983A486E
  ProductCode: SQLite Expert Professional 6 - 32bit_is1
- Architecture: x64
  InstallerUrl: https://www.sqliteexpert.com/v6/SQLiteExpertProSetup64.exe
  InstallerSha256: 389B35372E2136E64C50E3330F6329141406F963A1CAA98110EB48625C83DC7E
  ProductCode: SQLite Expert Professional 6 - 64bit_is1
ManifestType: installer
ManifestVersion: 1.12.0
