# Created with YamlCreate.ps1 Dumplings Mod
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: CoralCreek.SQLiteExpert.Personal
PackageVersion: 6.2.2.736
InstallerType: inno
Scope: machine
ReleaseDate: 2026-09-26
Installers:
- Architecture: x86
  InstallerUrl: https://www.sqliteexpert.com/v6/SQLiteExpertPersSetup32.exe
  InstallerSha256: 2346950F61849CFAC6D4EB687A521DB877B8404116F8FC8EA2FC30F32424BFE2
  ProductCode: SQLite Expert Personal 6 - 32bit_is1
- Architecture: x64
  InstallerUrl: https://www.sqliteexpert.com/v6/SQLiteExpertPersSetup64.exe
  InstallerSha256: B199829E699507EEF2DBDB46BC1F22A6D72D701FFB88D15D81A6D23C84F83EFF
  ProductCode: SQLite Expert Personal 6 - 64bit_is1
ManifestType: installer
ManifestVersion: 1.12.0
